# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='<function now at 0x7fdf286059d8>', max_length=128, verbose_name='Title')),
                ('img', models.ImageField(upload_to='')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Upload datetime')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
