# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpleimage',
            name='title',
            field=models.CharField(default='2016-11-17 20:43:40', max_length=128, verbose_name='Title'),
        ),
    ]
